# gazebo_ros_control:
#   pid_gains:
#     joint_turn1: {p: 100.0, i: 0.01, d: 10.0}
#     joint_turn2: {p: 100.0, i: 0.01, d: 10.0}
#     joint_turn3: {p: 100.0, i: 0.01, d: 10.0}
#     joint_turn4: {p: 100.0, i: 0.01, d: 10.0}