; Auto-generated. Do not edit!


(cl:in-package demo01_action-msg)


;//! \htmlinclude AddintsResult.msg.html

(cl:defclass <AddintsResult> (roslisp-msg-protocol:ros-message)
  ((result
    :reader result
    :initarg :result
    :type cl:integer
    :initform 0))
)

(cl:defclass AddintsResult (<AddintsResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <AddintsResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'AddintsResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name demo01_action-msg:<AddintsResult> is deprecated: use demo01_action-msg:AddintsResult instead.")))

(cl:ensure-generic-function 'result-val :lambda-list '(m))
(cl:defmethod result-val ((m <AddintsResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader demo01_action-msg:result-val is deprecated.  Use demo01_action-msg:result instead.")
  (result m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <AddintsResult>) ostream)
  "Serializes a message object of type '<AddintsResult>"
  (cl:let* ((signed (cl:slot-value msg 'result)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <AddintsResult>) istream)
  "Deserializes a message object of type '<AddintsResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'result) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<AddintsResult>)))
  "Returns string type for a message object of type '<AddintsResult>"
  "demo01_action/AddintsResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'AddintsResult)))
  "Returns string type for a message object of type 'AddintsResult"
  "demo01_action/AddintsResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<AddintsResult>)))
  "Returns md5sum for a message object of type '<AddintsResult>"
  "034a8e20d6a306665e3a5b340fab3f09")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'AddintsResult)))
  "Returns md5sum for a message object of type 'AddintsResult"
  "034a8e20d6a306665e3a5b340fab3f09")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<AddintsResult>)))
  "Returns full string definition for message of type '<AddintsResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%#2.最终反馈响应变量~%int32 result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'AddintsResult)))
  "Returns full string definition for message of type 'AddintsResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%#2.最终反馈响应变量~%int32 result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <AddintsResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <AddintsResult>))
  "Converts a ROS message object to a list"
  (cl:list 'AddintsResult
    (cl:cons ':result (result msg))
))
