; Auto-generated. Do not edit!


(cl:in-package demo01_action-msg)


;//! \htmlinclude AddintsFeedback.msg.html

(cl:defclass <AddintsFeedback> (roslisp-msg-protocol:ros-message)
  ((progress_bar
    :reader progress_bar
    :initarg :progress_bar
    :type cl:float
    :initform 0.0))
)

(cl:defclass AddintsFeedback (<AddintsFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <AddintsFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'AddintsFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name demo01_action-msg:<AddintsFeedback> is deprecated: use demo01_action-msg:AddintsFeedback instead.")))

(cl:ensure-generic-function 'progress_bar-val :lambda-list '(m))
(cl:defmethod progress_bar-val ((m <AddintsFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader demo01_action-msg:progress_bar-val is deprecated.  Use demo01_action-msg:progress_bar instead.")
  (progress_bar m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <AddintsFeedback>) ostream)
  "Serializes a message object of type '<AddintsFeedback>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'progress_bar))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <AddintsFeedback>) istream)
  "Deserializes a message object of type '<AddintsFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'progress_bar) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<AddintsFeedback>)))
  "Returns string type for a message object of type '<AddintsFeedback>"
  "demo01_action/AddintsFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'AddintsFeedback)))
  "Returns string type for a message object of type 'AddintsFeedback"
  "demo01_action/AddintsFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<AddintsFeedback>)))
  "Returns md5sum for a message object of type '<AddintsFeedback>"
  "ac7532a8a8f0d2be4f5284d94fee2d59")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'AddintsFeedback)))
  "Returns md5sum for a message object of type 'AddintsFeedback"
  "ac7532a8a8f0d2be4f5284d94fee2d59")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<AddintsFeedback>)))
  "Returns full string definition for message of type '<AddintsFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#3.连续反馈变量~%float64 progress_bar~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'AddintsFeedback)))
  "Returns full string definition for message of type 'AddintsFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#3.连续反馈变量~%float64 progress_bar~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <AddintsFeedback>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <AddintsFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'AddintsFeedback
    (cl:cons ':progress_bar (progress_bar msg))
))
