; Auto-generated. Do not edit!


(cl:in-package demo01_action-msg)


;//! \htmlinclude AddintsGoal.msg.html

(cl:defclass <AddintsGoal> (roslisp-msg-protocol:ros-message)
  ((num
    :reader num
    :initarg :num
    :type cl:integer
    :initform 0))
)

(cl:defclass AddintsGoal (<AddintsGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <AddintsGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'AddintsGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name demo01_action-msg:<AddintsGoal> is deprecated: use demo01_action-msg:AddintsGoal instead.")))

(cl:ensure-generic-function 'num-val :lambda-list '(m))
(cl:defmethod num-val ((m <AddintsGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader demo01_action-msg:num-val is deprecated.  Use demo01_action-msg:num instead.")
  (num m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <AddintsGoal>) ostream)
  "Serializes a message object of type '<AddintsGoal>"
  (cl:let* ((signed (cl:slot-value msg 'num)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <AddintsGoal>) istream)
  "Deserializes a message object of type '<AddintsGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'num) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<AddintsGoal>)))
  "Returns string type for a message object of type '<AddintsGoal>"
  "demo01_action/AddintsGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'AddintsGoal)))
  "Returns string type for a message object of type 'AddintsGoal"
  "demo01_action/AddintsGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<AddintsGoal>)))
  "Returns md5sum for a message object of type '<AddintsGoal>"
  "54b3c80efd6fae6e6ffff8a4b9facd69")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'AddintsGoal)))
  "Returns md5sum for a message object of type 'AddintsGoal"
  "54b3c80efd6fae6e6ffff8a4b9facd69")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<AddintsGoal>)))
  "Returns full string definition for message of type '<AddintsGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#1.目标数据变量~%int32 num~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'AddintsGoal)))
  "Returns full string definition for message of type 'AddintsGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#1.目标数据变量~%int32 num~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <AddintsGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <AddintsGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'AddintsGoal
    (cl:cons ':num (num msg))
))
