// Generated by gencpp from file agv_sim_control_test/cmd_xyw.msg
// DO NOT EDIT!


#ifndef AGV_SIM_CONTROL_TEST_MESSAGE_CMD_XYW_H
#define AGV_SIM_CONTROL_TEST_MESSAGE_CMD_XYW_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace agv_sim_control_test
{
template <class ContainerAllocator>
struct cmd_xyw_
{
  typedef cmd_xyw_<ContainerAllocator> Type;

  cmd_xyw_()
    : vx(0.0)
    , vy(0.0)
    , vw(0.0)  {
    }
  cmd_xyw_(const ContainerAllocator& _alloc)
    : vx(0.0)
    , vy(0.0)
    , vw(0.0)  {
  (void)_alloc;
    }



   typedef float _vx_type;
  _vx_type vx;

   typedef float _vy_type;
  _vy_type vy;

   typedef float _vw_type;
  _vw_type vw;





  typedef boost::shared_ptr< ::agv_sim_control_test::cmd_xyw_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agv_sim_control_test::cmd_xyw_<ContainerAllocator> const> ConstPtr;

}; // struct cmd_xyw_

typedef ::agv_sim_control_test::cmd_xyw_<std::allocator<void> > cmd_xyw;

typedef boost::shared_ptr< ::agv_sim_control_test::cmd_xyw > cmd_xywPtr;
typedef boost::shared_ptr< ::agv_sim_control_test::cmd_xyw const> cmd_xywConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agv_sim_control_test::cmd_xyw_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agv_sim_control_test::cmd_xyw_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace agv_sim_control_test

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'agv_sim_control_test': ['/home/wangxiao/learn_ws/src/agv_sim/agv_sim_control_test/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::agv_sim_control_test::cmd_xyw_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_sim_control_test::cmd_xyw_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_sim_control_test::cmd_xyw_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_sim_control_test::cmd_xyw_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_sim_control_test::cmd_xyw_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_sim_control_test::cmd_xyw_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agv_sim_control_test::cmd_xyw_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7b05b0d6d04a58ba4ceea97f1ea581c4";
  }

  static const char* value(const ::agv_sim_control_test::cmd_xyw_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7b05b0d6d04a58baULL;
  static const uint64_t static_value2 = 0x4ceea97f1ea581c4ULL;
};

template<class ContainerAllocator>
struct DataType< ::agv_sim_control_test::cmd_xyw_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv_sim_control_test/cmd_xyw";
  }

  static const char* value(const ::agv_sim_control_test::cmd_xyw_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agv_sim_control_test::cmd_xyw_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 vx\n\
float32 vy\n\
float32 vw\n\
";
  }

  static const char* value(const ::agv_sim_control_test::cmd_xyw_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agv_sim_control_test::cmd_xyw_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vx);
      stream.next(m.vy);
      stream.next(m.vw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cmd_xyw_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agv_sim_control_test::cmd_xyw_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agv_sim_control_test::cmd_xyw_<ContainerAllocator>& v)
  {
    s << indent << "vx: ";
    Printer<float>::stream(s, indent + "  ", v.vx);
    s << indent << "vy: ";
    Printer<float>::stream(s, indent + "  ", v.vy);
    s << indent << "vw: ";
    Printer<float>::stream(s, indent + "  ", v.vw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGV_SIM_CONTROL_TEST_MESSAGE_CMD_XYW_H
